# Docker Compose configuration for YoLink Web UI

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=release
      - YOLINK_CLIENT_SECRET=
      - YOLINK_CLIENT_ID=
    env_file:
      - path: ./backend/.env
        required: false
    volumes:
      - ./backend/.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/devices"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8080
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Development override - uncomment for development mode
  # frontend-dev:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     - NODE_ENV=development
  #     - VITE_API_URL=http://localhost:8080
  #   volumes:
  #     - ./frontend/src:/app/src:ro
  #     - ./frontend/public:/app/public:ro
  #   depends_on:
  #     - backend
  #   restart: unless-stopped

networks:
  default:
    name: yolink-network